module.exports = {
    url: 'https://deseretbook.net/signup',
    elements: {
        'emailSignUp' : 'input[id="spree_user_email"]',
        'firstName' : 'input[name="spree_user[first_name]"]',
        'lastName' : 'input[id="spree_user_last_name"]',
        'monthDropdown' : 'select#spree_user_birth_date_2i option[value="10"]',
        'birthday' : 'select[id="spree_user_birth_date_2i"]',
        'dayDropdown' : 'select[id="spree_user_birth_date_3i"] option[value="1"]',
        'password' : 'input[name="spree_user[password]"]',
        'confirmPassword' : 'input[name="spree_user[password_confirmation]"]',
        'privacyPolicy' : 'input[type="checkbox"]',
        'createButton' : 'input[type="submit"]',
        'flashSaveNew' :'div[class="flash alert alert-info"]',
        'myAccount' : 'a[href="/account"]',
        'addresses' : 'span[class="translation_missing"]',
        'addNewAddress' : 'a[href="/account/addresses/new"]',
        'addressFirstName' : 'input[id="address_firstname"]',
        'addressLastName' : 'input[id="address_lastname"]',
        'addressLineOne' : 'input[id="address_address1"]',
        'addressCity' : 'input[id="address_city"]',
        'addressState' : 'select[id="address_state_id"] option[value="18"]',
        'addressZip' : 'input[id="address_zipcode"]',
        'checkBoxBill' : 'input[id="address_default_bill_address"]',
        'checkBoxShip' : 'input[id="address_default_ship_address"]',
        'addressPhone' : 'input[id="address_phone"]',
        'addressSave' : 'input[type="submit"]',
        'flashSaveAddresses' : 'div[class="flash alert alert-success"]', 
        'headerMyAddresses' : 'h1[id="my-account-title"]',
        'headerMySub' : 'a[href="/account/subscriptions"]',
        'settingsBuyNow' : 'a[href="/account/buy_now"]',
        'headerBuyNow' : 'h1[id="my-account-title"]',
        'nameBuyNow' : 'input[name="payment_source[name]"]',
        'ccBuyNow' : 'input[id="credit-card-number"]',
        'expirationBuyNow' : 'input[id="expiration"]',
        'cvvBuyNow' : 'input[id="cvv"]',
        'addressBuyNow' : 'input[name="billing_address[address1]"]',
        'cityBuyNow' : 'input[id="billing_address_city"]',
        'stateBuyNow' : 'select[id="billing_address_state_id"] option[value="18"]',
        'zipBuyNow' : 'input[id="billing_address_zipcode"]',
        'phoneBuyNow' : 'input[id="billing_address_phone"]',
        'activateBuyNow' : 'input[class="btn btn-emphasis"]',
        'flashBuyNow' : 'div[class="flash alert alert-success"]',
        'logOut' : 'a[href="/logout"]',
        'flashLogOut' : 'div[class="flash alert alert-info"]',
        'searchField' : 'input[type="search"]',
        'typeSearch' : 'placeholder="What can we help you find?',
        'search' : 'svg[class="db-svg-icon is-search   "]',
        'selectFirst' : 'span[class="product-fallback has-drop-shadow"]',
        'theImpossible' : 'input[id="variant_id_125918"]',
        'productHeader' :  'span[class="product-fallback has-drop-shadow"]',       
        'addToCartBtn' : 'button[class="btn btn-lg btn-primary btn-block text-uppercase btn-add-to-cart btn-gradient js-btn-add-to-cart variant-cart-submit"]',
        'proceedChckBtn' :'a[class="button is-primary      is-fullwidth  "]',
        'chckoutBtn' : 'a[class="btn btn-primary btn-lg btn-checkout"]',
        'firstnameChck' : 'input[id="order_bill_address_attributes_firstname"]',
        'lastnameChck' : 'input[id="order_bill_address_attributes_lastname"]',
        'streetChck' : 'input[name="order[bill_address_attributes][address1]"]',
        'cityChck' : 'input[name="order[bill_address_attributes][city]"]',
        'stateChck' : 'select[id="order_bill_address_attributes_state_id"] option[value="18"]',
        'zipChck' : 'input[name="order[bill_address_attributes][zipcode]"]',
        'phoneChck' :'input[name="order[bill_address_attributes][phone]"]',
        'readFreeBtn' : 'span[class="text-uppercase js-btn-plus-text"]',
        'bsHeader' : 'img[class="logo-lg"]',
        'buyNowBtn' : 'a[class="btn btn-lg text-uppercase btn-block btn-gradient btn-primary js-btn-buy-now"]',
        'confirmBtn' : 'a[class="btn btn-lg text-uppercase btn-block btn-gradient btn-primary js-btn-buy-now"]',
        'cardOnFile' : 'a[href="/account/cards"]',
        'headerSavedcc' :'h1[id="my-account-title"]',
        'nameCC' : 'input[id="name_on_card_35"]',
        'inputCC' :'input[name="credit-card-number"]',
        'ccExp' :'input[class="expirationDate"]',
        'ccCvv' :'input[id="cvv"]',
        'ccAddress' :'input[id="bill_address_address1"]',
        'ccCity' :'input[id="bill_address_city"]',
        'ccState' :'select[id="bill_address_state_id"] option[value="18"]',
        'ccZip' :'input[name="bill_address[zipcode]"]',
        'ccPhone' :'input[id="bill_address_phone"]',
        'ccSaveBtn' :'input[class="btn btn-primary"]',
        'flashCCsaved' :'div[class="flash alert alert-info"]',
        'logIn' : 'a[href="/login"]',
        'loginEmail' : 'input[name="spree_user[email]"]',
        'loginPass' : 'input[name="spree_user[password]"]',
        'loginBtn' : 'input[class="btn btn-primary"]',
        'flashLogin' : 'div[class="flash alert alert-success"]',
        'loginHeader' : 'div[class="panel-heading"]',




    }
}